var CTQQuestionsMatrix = [
    'People in my family called me things like "stupid", "lazy", or "ugly"',
    "I thought that my parents wished I had never been born",
    "I felt that someone in my family hated me",
    "People in my family said hurtful or insulting things to me",
    "I believe I was emotionally abused",
    "I got hit so hard by someone in my family that I had to see a doctor or go to the hospital",
    "People in my family hit me so hard that it left me with bruises or marks",
    "I was punished with a belt, a board, a cord, or some other hard object",
    "I believe that I was physically abused",
    "I got hit or beaten so badly that it was noticed by someone like a teacher, neighbour, or doctor",
    "Someone tried to touch me in a sexual way, or tried to make me touch them",
    "Someone threatened to hurt me or tell lies about me unless I did something sexual with them",
    "Someone tried to make me do sexual things or watch sexual things",
    "Someone molested me",
    "I believe that I was sexually abused",
    "There was someone in my family who helped me feel that I was important or special",
    "I felt loved",
    "People in my family looked out for each other",
    "People in my family felt close to each other",
    "My family was a source of strength and support",
    "I didn't have enough to eat",
    "I knew that there was someone to take care of me and protect me",
    "My parents were too drunk or high to take care of the family",
    "I had to wear dirty clothes",
    "There was someone to take me to the doctor if I needed it",
    "There was nothing I wanted to change about my family",
    "I had the perfect childhood",
    "I had the best family in the world"

]