var QUICQuestionsMatrix1 = [
    "I had a set morning routine on school days (i.e., I usually did the same thing each day to get ready)",
    "My parents were often late to pick me up (e.g. from school, aftercare or sports)",
    "My parents kept track of what I ate (e.g., made sure that I didn’t skip meals or tried to make sure I ate healthy food)",
    "My family ate a meal together most days",
    "My parents tried to make sure I got a good night's sleep (e.g., I had a regular bed time, my parents checked to make sure I went to sleep)",
    "I had a bedtime routine (e.g., my parents tucked me in, my parents read me a book, I took a bath)",
    "In my afterschool or free time hours at least one of my parents knew what I was doing",
    "I usually knew when my parents were going to be home",
    "At least one of my parents regularly checked that I did my homework"
]

var QUICQuestionsMatrix2 = [
    "At least one of my parents regularly kept track of my school progress",
    "At least one of my parents had punishments that were unpredictable",
    "I often wondered whether or not one of my parents would come home at the end of the day",
    "There were often people coming and going in my house that I did not expect to be there",
    "At least one parent made time each day to see how I was doing",
    "My family planned activities to do together",
    "At least one of my parents would plan something for the family, but then not follow through with the plan",
    "My family had holiday traditions that we did every year (e.g., cooking a special food at a particular time of year/decorate the house the same way)",
    "There was a long period of time when I didn’t see one of my parents (e.g. military deployment, jail time, custody arrangements)",
    "I experienced changes in my custody arrangement",
    "I moved frequently",
    "At least one of my parents changed jobs frequently",
    "There were times when one of my parents was unemployed and couldn’t find a job even though he/she wanted one",
    "There was a period of time when I often worried that I was not going to have enough food to eat",
    "There was a period of time when I often worried that my family would not have enough money to pay for necessities like clothing or bills",
    "There was a period of time when I did not feel safe in my home",
    "I changed schools frequently",
    "I changed schools mid-year",
    "My parents had a stable relationship with each other",
    "My parents got divorced",
    "At least one of my parents had many romantic partners",
    "At least one of my parents was disorganized",
    "At least one of my parents was unpredictable",
    "For at least one of my parents, when they were upset I did not know how they would act",
    "One of my parents could go from calm to furious in an instant",
    "One of my parents could go from calm to stressed or nervous in an instant",
    "I lived in a clean house",
    "I lived in a cluttered house (e.g., piles of stuff everywhere)",
    "In my house things I needed were often misplaced so that I could not find them"
]