
var SCL90QuestionsMatrix = [
    "Headaches",
    "Nervousness or shakiness inside",
    "Unwanted thoughts, words, or ideas that won’t leave your mind",
    "Faintness or dizziness",
    "Loss of sexual interest or pleasure",
    "Feeling critical of others",
    "The idea that someone else can control your thoughts",
    "Feeling others are to blame for most of your troubles",
    "Trouble remembering things",
    "Worried about sloppiness or carelessness",
    "Feeling easily annoyed or irritated",
    "Pains in heart or chest",
    "Feeling afraid in open spaces or on the streets",
    "Feeling low in energy or slowed down",
    "Thoughts of ending your life",
    "Hearing voices that other people do not hear",
    "Trembling",
    "Feeling that most people cannot be trusted",
    "Poor appetite",
    "Crying easily",
    "Feeling shy or uneasy with the opposite sex",
    "Feeling of being trapped or caught",
    "Suddenly scared for no reason",
    "Temper outbursts that you could not control",
    "Feeling afraid to go out of your house alone",
    "Blaming yourself for things",
    "Pains in lower back",
    "Feeling blocked in getting things done",
    "Feeling lonely",
    "Feeling blue",
    "Worrying too much about things",
    "Feeling no interest in things",
    "Feeling fearful",
    "Your feelings being easily hurt",
    "Other people being aware of your private thoughts",
    "Feeling others do not understand you or are unsympathetic",
    "Feeling that people are unfriendly or dislike you",
    "Having to do things very slowly to insure correctness",
    "Heart pounding or racing",
    "Nausea or upset stomach",
    "Feeling inferior to others",
    "Soreness of your muscles",
    "Feeling that you are watched or talked about by others",
    "Trouble falling asleep",
    "Having to check and double-check what you do",
    "Difficulty making decisions",
    "Feeling afraid to travel on buses, subways, trains",
    "Trouble getting your breath",
    "Hot or cold spells",
    "Having to avoid certain things, places, or activities because they frighten you",
    "Your mind going blank",
    "Numbness or tingling in parts of your body",
    "A lump in your throat",
    "Feeling hopeless about the future",
    "Trouble concentrating",
    "Feeling weak in parts of your body",
    "Feeling tense or keyed up",
    "Heavy feelings in your arms or legs",
    "Thoughts of death or dying",
    "Overeating",
    "Feeling uneasy when people are watching or talking about you",
    "Having thoughts that are not your own",
    "Having urges to beat, injure, or harm someone",
    "Awakening in the early morning",
    "Having to repeat the same actions such as touching, counting, washing",
    "Sleep that is restless or disturbed",
    "Having urges to break or smash things",
    "Having ideas or beliefs that others do not share",
    "Feeling very self-conscious with others",
    "Feeling uneasy in crowds, such as shopping or at a movie",
    "Feeling everything is an effort",
    "Spells of terror or panic",
    "Feeling uncomfortable about eating or drinking in public",
    "Getting into frequent arguments",
    "Feeling nervous when you are left alone",
    "Others not giving you proper credit for your achievements",
    "Feeling lonely even when you are with people",
    "Feeling so restless you couldn’t sit still",
    "Feelings of worthlessness",
    "Feeling that familiar things are strange or unreal",
    "Shouting or throwing things",
    "Feeling afraid you will faint in public",
    "Feeling that people will take advantage of you if you let them",
    "Having thoughts about sex that bother you a lot",
    "The idea that you should be punished for your sins",
    "Feeling pushed to get things done",
    "The idea that something serious is wrong with your body",
    "Never feeling close to another person",
    "Feelings of guilt",
    "The idea that something is wrong with your mind"
]