var SPSRQQuestionsMatrix = [
    "Do you often refrain from doing something because you are afraid of it being illegal?",
    "Does the good prospect of obtaining money motivate you strongly to do some things?",
    "Do you prefer not to ask for something you are not sure you will obtain it?",
    "Are you frequently encouraged to act by the possibility of being valued in your work, in your studies, with your friends or with your family?",
    "Are you often afraid of new or unexpected situations?",
    "Do you often meet people that you find physically attractive?",
    "Is it difficult for you to telephone someone you do not know?",
    "Do you like taking some drugs because of the pleasure you get from them?",
    "Do you often renounce your rights when you know you can avoid a quarrel with a person or an organization?",
    "Do you often do things to be praised?",
    "As a child, were you troubled by punishments at home or in school?",
    "Do you like being the center of attention at a party or a social meeting?",
    "In tasks that you are not prepared for, do you attach great importance to the possibility of failure?",
    "Do you spend a lot of your time on obtaining a good image?",
    "Are you easily discouraged in difficult situations?",
    "Do you need people to show their affection for you all the time?",
    "Are you a shy person?",
    "When you are with a group, do you try to make your opinions the most intelligent or the funniest?",
    "Whenever possible, do you avoid demonstrating your skills for fear of being embarrassed?",
    "Do you often take the opportunity to pick up people you find attractive?",
    "When you are with a group, do you have difficulties selecting a good topic to talk about?",
    "As a child, did you do a lot of things to get people’s approval?",
    "Is it often difficult for you to fall asleep when you think about things you have done or must do?",
    "Does the possibility of social advancement, move you to action, even if this involves not playing fair?",
    "Do you think a lot before complaining in a restaurant if your meal is not well prepared?",
    "Do you generally give preference to those activities that imply an immediate gain?",
    "Would you be bothered if you had to return to a store when you noticed you were given the wrong change?",
    "Do you often have trouble resisting the temptation of doing forbidden things?",
    "Whenever you can, do you avoid going to unknown places?",
    "Do you like to compete and do everything you can do to win?",
    "Are you often worried by things you said or did?",
    "Is it easy for you to associate tastes and smells to very pleasant events?",
    "Would it be difficult for you to ask your boss for a raise (salary increase)?",
    "Are there a large number of objects or sensations that remind you of pleasant events?",
    "Do you generally avoid speaking in public?",
    "When you start to play with a slot machine, is it often difficult for you to stop?",
    "Do you, on a regular basis, think that you could do more things if it was not for your insecurity or fear?",
    "Do you sometimes do things for quick gains?",
    "Comparing yourself to people you know, are you afraid of many things?",
    "Does your attention easily stray from your work in the presence of an attractive stranger?",
    "Do you often find yourself worrying about things to the extent that performance in intellectual abilities is impaired?",
    "Are you interested in money to the point of being able to do risky jobs?",
    "Do you often refrain from doing something you like in order not to be rejected or disapproved by others?",
    "Do you like to put competitive ingredients in all of your activities?",
    "Generally, do you pay more attention to threats than to pleasant events?",
    "Would you like to be a socially powerful person?",
    "Do you often refrain from doing something because of your fear of being embarrassed?",
    "Do you like displaying your physical abilities even though this may involve danger?"
]